/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const AttendanceRecord = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Text,
  'date' : IDL.Text,
  'hour' : IDL.Text,
  'regNo' : IDL.Text,
});
export const DisciplineFlag = IDL.Record({
  'id' : IDL.Nat,
  'reportedBy' : IDL.Text,
  'timestamp' : IDL.Text,
  'regNo' : IDL.Text,
  'violationType' : IDL.Text,
});
export const GateViolation = IDL.Record({
  'id' : IDL.Nat,
  'recordedBy' : IDL.Text,
  'timestamp' : IDL.Text,
  'regNo' : IDL.Text,
  'violationType' : IDL.Text,
});
export const Student = IDL.Record({
  'dept' : IDL.Text,
  'name' : IDL.Text,
  'year' : IDL.Text,
  'section' : IDL.Text,
  'regNo' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
export const Stats = IDL.Record({
  'totalDisciplineFlags' : IDL.Nat,
  'totalGateViolations' : IDL.Nat,
  'totalStudents' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addAttendanceRecord' : IDL.Func([AttendanceRecord], [], []),
  'addDisciplineFlag' : IDL.Func([DisciplineFlag], [], []),
  'addGateViolation' : IDL.Func([GateViolation], [], []),
  'addOrUpdateStudent' : IDL.Func([Student], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'getAllDisciplineFlags' : IDL.Func([], [IDL.Vec(DisciplineFlag)], ['query']),
  'getAllGateViolations' : IDL.Func([], [IDL.Vec(GateViolation)], ['query']),
  'getAttendanceByDeptAndDate' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getAttendanceByRegNo' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(AttendanceRecord)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDisciplineFlagsByRegNo' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(DisciplineFlag)],
      ['query'],
    ),
  'getGateViolationsByRegNo' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(GateViolation)],
      ['query'],
    ),
  'getStats' : IDL.Func([], [Stats], ['query']),
  'getStudentByRegNo' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
  'getTodayAttendancePercentage' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
  'getTotalDisciplineFlags' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'removeStudent' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchStudentsByName' : IDL.Func([IDL.Text], [IDL.Vec(Student)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const AttendanceRecord = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Text,
    'date' : IDL.Text,
    'hour' : IDL.Text,
    'regNo' : IDL.Text,
  });
  const DisciplineFlag = IDL.Record({
    'id' : IDL.Nat,
    'reportedBy' : IDL.Text,
    'timestamp' : IDL.Text,
    'regNo' : IDL.Text,
    'violationType' : IDL.Text,
  });
  const GateViolation = IDL.Record({
    'id' : IDL.Nat,
    'recordedBy' : IDL.Text,
    'timestamp' : IDL.Text,
    'regNo' : IDL.Text,
    'violationType' : IDL.Text,
  });
  const Student = IDL.Record({
    'dept' : IDL.Text,
    'name' : IDL.Text,
    'year' : IDL.Text,
    'section' : IDL.Text,
    'regNo' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text, 'role' : IDL.Text });
  const Stats = IDL.Record({
    'totalDisciplineFlags' : IDL.Nat,
    'totalGateViolations' : IDL.Nat,
    'totalStudents' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addAttendanceRecord' : IDL.Func([AttendanceRecord], [], []),
    'addDisciplineFlag' : IDL.Func([DisciplineFlag], [], []),
    'addGateViolation' : IDL.Func([GateViolation], [], []),
    'addOrUpdateStudent' : IDL.Func([Student], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'getAllDisciplineFlags' : IDL.Func(
        [],
        [IDL.Vec(DisciplineFlag)],
        ['query'],
      ),
    'getAllGateViolations' : IDL.Func([], [IDL.Vec(GateViolation)], ['query']),
    'getAttendanceByDeptAndDate' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getAttendanceByRegNo' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(AttendanceRecord)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDisciplineFlagsByRegNo' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(DisciplineFlag)],
        ['query'],
      ),
    'getGateViolationsByRegNo' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(GateViolation)],
        ['query'],
      ),
    'getStats' : IDL.Func([], [Stats], ['query']),
    'getStudentByRegNo' : IDL.Func([IDL.Text], [IDL.Opt(Student)], ['query']),
    'getTodayAttendancePercentage' : IDL.Func([IDL.Text], [IDL.Nat], ['query']),
    'getTotalDisciplineFlags' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'removeStudent' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchStudentsByName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Student)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };